// ---------------------------------------------------------------------------
// Blog data model + helpers.
//
// Articles are authored (and generated by the publishing automation) as typed
// content BLOCKS rather than free HTML/markdown, so every post renders through
// one styled ArticleRenderer and shares the site's design system. The same
// schema is what the automation emits, so authoring and generation agree.
//
// Posts live in content/blog/<slug>.ts and are registered in content/blog/index.ts.
// ---------------------------------------------------------------------------

// Inline text in paragraphs/list items/table cells supports a tiny, safe subset:
//   [label](https://url)  -> link (external opens in a new tab; internal routes)
//   **bold**              -> emphasis
// Nothing else is interpreted, so author/generated text can't inject markup.
export type Inline = string;

export type ImageCredit = {
  source: string; // e.g. "Pexels", "Wikimedia Commons", "Company owned"
  sourceUrl: string; // page the asset came from
  author: string; // photographer / creator
  license: string; // e.g. "Pexels License", "CC BY-SA 4.0"
  licenseUrl: string;
  downloaded: string; // ISO date
  attributionRequired: boolean;
  depicts: string; // what the image genuinely shows (honesty check)
};

export type Source = {
  title: string;
  url: string;
  accessed: string; // ISO date verified
  supports: string; // the claim(s) this source backs
};

export type Block =
  | { type: 'p'; text: Inline }
  | { type: 'h2'; text: string; id?: string }
  | { type: 'h3'; text: string; id?: string }
  | { type: 'ul'; items: Inline[] }
  | { type: 'ol'; items: Inline[] }
  | { type: 'table'; caption?: string; headers: string[]; rows: Inline[][] }
  | { type: 'image'; src: string; alt: string; caption?: Inline; credit?: ImageCredit; width?: number; height?: number }
  | { type: 'callout'; variant: 'tip' | 'note' | 'warning'; title?: string; text: Inline }
  | { type: 'quote'; text: string; cite?: string }
  | { type: 'cta'; label: string; href: string; note?: string }
  | { type: 'faq'; items: { q: string; a: Inline }[] };

export type BlogCategory =
  | 'Planning'
  | 'Destinations'
  | 'Activities'
  | 'Wildlife & Nature'
  | 'Beaches'
  | 'Seasons & Weather'
  | 'Practical';

export const BLOG_CATEGORIES: BlogCategory[] = [
  'Planning', 'Destinations', 'Activities', 'Wildlife & Nature', 'Beaches', 'Seasons & Weather', 'Practical',
];

export type BlogPost = {
  slug: string;
  title: string; // H1 + og:title
  metaTitle: string; // <title>
  description: string; // meta description (~150-160 chars)
  category: BlogCategory;
  tags: string[];
  primaryQuery: string; // the search query this answers
  intent: string; // one primary search intent
  author: { name: string; role: string };
  published: string; // ISO date
  updated?: string; // ISO date, only when content meaningfully changed
  reviewBy?: string; // internal refresh date
  hero: { src: string; alt: string; caption?: Inline; credit?: ImageCredit; width?: number; height?: number; focal?: string };
  excerpt: string; // card + list description
  body: Block[];
  sources: Source[]; // verifiable references with access dates
  relatedTours: string[]; // tour slugs (lib/tours)
  relatedDestinations: string[]; // destination slugs (lib/seo-content)
  relatedPosts: string[]; // post slugs
  cta: { label: string; href: string }; // primary contextual CTA
  featured?: boolean;
  draft?: boolean; // excluded from indexes, sitemap, RSS until false
};

// --- Registry (posts registered in content/blog) --------------------------
import { POSTS } from '../content/blog';

const includeDrafts =
  typeof process !== 'undefined' && process.env?.EXPO_PUBLIC_BLOG_DRAFTS === '1';

/** Published posts, newest first. Drafts hidden unless EXPO_PUBLIC_BLOG_DRAFTS=1. */
export function getAllPosts(): BlogPost[] {
  return [...POSTS]
    .filter((p) => includeDrafts || !p.draft)
    .sort((a, b) => (a.published < b.published ? 1 : -1));
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return POSTS.find((p) => p.slug === slug && (includeDrafts || !p.draft));
}

export function getFeaturedPost(): BlogPost | undefined {
  const all = getAllPosts();
  return all.find((p) => p.featured) ?? all[0];
}

export function getPostsByCategory(category: BlogCategory): BlogPost[] {
  return getAllPosts().filter((p) => p.category === category);
}

/** Categories that actually have at least one published post. */
export function getActiveCategories(): { category: BlogCategory; count: number }[] {
  const posts = getAllPosts();
  return BLOG_CATEGORIES.map((category) => ({
    category,
    count: posts.filter((p) => p.category === category).length,
  })).filter((c) => c.count > 0);
}

export function getRelatedPosts(post: BlogPost, limit = 3): BlogPost[] {
  const explicit = post.relatedPosts
    .map((s) => getPostBySlug(s))
    .filter((p): p is BlogPost => !!p && p.slug !== post.slug);
  if (explicit.length >= limit) return explicit.slice(0, limit);
  // Backfill with same-category posts.
  const sameCat = getAllPosts().filter(
    (p) => p.slug !== post.slug && p.category === post.category && !explicit.includes(p),
  );
  return [...explicit, ...sameCat].slice(0, limit);
}

const WORDS_PER_MINUTE = 220;

function inlineToPlain(s: Inline): string {
  return s.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1').replace(/\*\*([^*]+)\*\*/g, '$1');
}

function blockWordCount(b: Block): number {
  const count = (s: string) => inlineToPlain(s).trim().split(/\s+/).filter(Boolean).length;
  switch (b.type) {
    case 'p': return count(b.text);
    case 'h2': case 'h3': return count(b.text);
    case 'ul': case 'ol': return b.items.reduce((n, i) => n + count(i), 0);
    case 'table': return b.rows.flat().reduce((n, c) => n + count(c), 0) + b.headers.reduce((n, h) => n + count(h), 0);
    case 'callout': return count(b.text) + (b.title ? count(b.title) : 0);
    case 'quote': return count(b.text);
    case 'faq': return b.items.reduce((n, i) => n + count(i.q) + count(i.a), 0);
    default: return 0;
  }
}

export function readingTimeMinutes(post: BlogPost): number {
  const words = post.body.reduce((n, b) => n + blockWordCount(b), 0) + inlineToPlain(post.excerpt).split(/\s+/).length;
  return Math.max(1, Math.round(words / WORDS_PER_MINUTE));
}

export function wordCount(post: BlogPost): number {
  return post.body.reduce((n, b) => n + blockWordCount(b), 0);
}

export function slugifyHeading(text: string): string {
  return text.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

export type TocEntry = { id: string; text: string; level: 2 | 3 };

/** Table of contents from H2/H3 blocks. Longer posts (>=3 headings) show one. */
export function tableOfContents(post: BlogPost): TocEntry[] {
  return post.body
    .filter((b): b is Extract<Block, { type: 'h2' | 'h3' }> => b.type === 'h2' || b.type === 'h3')
    .map((b) => ({ id: b.id ?? slugifyHeading(b.text), text: b.text, level: b.type === 'h2' ? 2 : 3 }));
}

/** Human date, e.g. "12 September 2026". */
export function formatDate(iso: string): string {
  const d = new Date(iso + (iso.length === 10 ? 'T00:00:00Z' : ''));
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' });
}
