// AUTO-GENERATED by scripts/sync-transfers.mjs on 2026-09-14 — do not edit by hand.
// Curated from the Viator Partner API (rating >= 4.5, reviews >= 20).
// Prices are indicative "from" values checked on the date below; Viator controls live pricing.
export const TRANSFERS_CHECKED_AT = "2026-09-14";
export interface TransferProduct {
  code: string; slug: string; title: string; origin: 'LIR' | 'SJO';
  zone: string; zoneName: string; service: 'private' | 'shared'; tripType: 'round-trip' | 'one-way' | 'either';
  rating: number; reviews: number; fromPrice: number | null; priceType: string;
  durationMin: number | null; durationMax: number | null; freeCancellation: boolean;
  image: { url: string; width: number; height: number; alt: string } | null;
}
export interface RentalProduct { code: string; slug: string; title: string; category: string; rating: number; reviews: number; freeCancellation: boolean; image: TransferProduct['image']; }
export const ZONES = [
  {
    "slug": "papagayo-coco",
    "name": "Papagayo, Playas del Coco & Hermosa"
  },
  {
    "slug": "flamingo-conchal",
    "name": "Flamingo, Potrero, Brasilito & Conchal"
  },
  {
    "slug": "tamarindo",
    "name": "Tamarindo, Langosta & Playa Grande"
  },
  {
    "slug": "nosara-samara",
    "name": "Nosara, Sámara & Carrillo"
  },
  {
    "slug": "liberia-riu",
    "name": "Liberia & RIU Guanacaste"
  },
  {
    "slug": "la-fortuna",
    "name": "La Fortuna & Arenal"
  }
] as const;
export const TRANSFERS: TransferProduct[] = [
  {
    "code": "282372P1",
    "slug": "costa-rica-private-guanacaste-airport-lir-arrival-transfer",
    "title": "Costa Rica Private Guanacaste Airport ( LIR ) Arrival Transfer",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "either",
    "rating": 4.85,
    "reviews": 486,
    "fromPrice": 4.2,
    "priceType": "PER_PERSON",
    "durationMin": 30,
    "durationMax": 45,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/r/33/f4/25/25/caption.jpg",
      "width": 720,
      "height": 480,
      "alt": "Costa Rica Private Guanacaste Airport ( LIR ) Arrival Transfer"
    }
  },
  {
    "code": "342457P2",
    "slug": "private-transfer-liberia-airport",
    "title": "Private Transfer Liberia Airport",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "either",
    "rating": 4.94,
    "reviews": 419,
    "fromPrice": 130,
    "priceType": "UNIT",
    "durationMin": 45,
    "durationMax": 85,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/15/bc/ee/c2.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transfer Liberia Airport"
    }
  },
  {
    "code": "8925P9",
    "slug": "private-transfer-from-liberia-airport-to-riu-guanacaste-hote",
    "title": "Private Transfer from Liberia Airport to RIU Guanacaste Hotel",
    "origin": "LIR",
    "zone": "liberia-riu",
    "zoneName": "Liberia & RIU Guanacaste",
    "service": "private",
    "tripType": "either",
    "rating": 4.89,
    "reviews": 175,
    "fromPrice": 80,
    "priceType": "UNIT",
    "durationMin": 40,
    "durationMax": 40,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/94/9f/56.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transfer from Liberia Airport to RIU Guanacaste Hotel"
    }
  },
  {
    "code": "54087P4",
    "slug": "private-transfer-int-airport-liberia-to-la-fortuna-from-1-to",
    "title": "Private Transfer Int. Airport Liberia To La Fortuna From 1 to 6 passengers",
    "origin": "LIR",
    "zone": "liberia-riu",
    "zoneName": "Liberia & RIU Guanacaste",
    "service": "private",
    "tripType": "either",
    "rating": 4.94,
    "reviews": 159,
    "fromPrice": 248.6,
    "priceType": "UNIT",
    "durationMin": null,
    "durationMax": null,
    "freeCancellation": false,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/36/c9/25.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transfer Int. Airport Liberia To La Fortuna From 1 to 6 passengers"
    }
  },
  {
    "code": "8925P13",
    "slug": "private-transfer-from-lir-airport-to-westin-playa-conchal-re",
    "title": "Private Transfer From LIR Airport to Westin Playa Conchal Resort",
    "origin": "LIR",
    "zone": "flamingo-conchal",
    "zoneName": "Flamingo, Potrero, Brasilito & Conchal",
    "service": "private",
    "tripType": "either",
    "rating": 4.72,
    "reviews": 134,
    "fromPrice": 145,
    "priceType": "UNIT",
    "durationMin": 60,
    "durationMax": 60,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/r/34/1d/d2/7b/caption.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transfer From LIR Airport to Westin Playa Conchal Resort"
    }
  },
  {
    "code": "144991P2",
    "slug": "liberia-airport-private-round-trip-transfer-with-free-drinks",
    "title": "Liberia Airport Private Round-Trip Transfer with Free Drinks",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "round-trip",
    "rating": 4.73,
    "reviews": 130,
    "fromPrice": 125,
    "priceType": "PER_PERSON",
    "durationMin": 60,
    "durationMax": 120,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/r/32/a5/c8/52/caption.jpg",
      "width": 720,
      "height": 480,
      "alt": "Liberia Airport Private Round-Trip Transfer with Free Drinks"
    }
  },
  {
    "code": "282372P4",
    "slug": "costa-rica-private-guanacaste-airport-lir-departure-transfer",
    "title": "Costa Rica Private Guanacaste Airport (LIR) Departure transfer",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "either",
    "rating": 4.68,
    "reviews": 105,
    "fromPrice": 3.5,
    "priceType": "PER_PERSON",
    "durationMin": 45,
    "durationMax": 45,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/15/84/ba/7d.jpg",
      "width": 720,
      "height": 480,
      "alt": "Costa Rica Private Guanacaste Airport (LIR) Departure transfer"
    }
  },
  {
    "code": "71911P6",
    "slug": "roundtrip-private-transfer-liberia-airport-to-your-selected-",
    "title": "RoundTrip Private Transfer - Liberia Airport to your selected location",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "round-trip",
    "rating": 4.95,
    "reviews": 91,
    "fromPrice": 295,
    "priceType": "UNIT",
    "durationMin": null,
    "durationMax": null,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/r/33/95/a5/b2/caption.jpg",
      "width": 720,
      "height": 480,
      "alt": "RoundTrip Private Transfer - Liberia Airport to your selected location"
    }
  },
  {
    "code": "12671P2",
    "slug": "round-trip-private-transfer-liberia-airport-san-jose-to-hote",
    "title": "Round-Trip Private Transfer Liberia Airport-San Jose to Hotels or Private Houses",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "round-trip",
    "rating": 4.98,
    "reviews": 91,
    "fromPrice": 187,
    "priceType": "UNIT",
    "durationMin": 60,
    "durationMax": 60,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0a/9a/08/e1.jpg",
      "width": 720,
      "height": 480,
      "alt": "Round-Trip Private Transfer Liberia Airport-San Jose to Hotels or Private Houses"
    }
  },
  {
    "code": "212811P2",
    "slug": "private-transfer-from-liberia-airport",
    "title": "Private transfer from Liberia Airport",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "either",
    "rating": 4.86,
    "reviews": 79,
    "fromPrice": 5,
    "priceType": "PER_PERSON",
    "durationMin": 60,
    "durationMax": 90,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/e8/b6/c0.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private transfer from Liberia Airport"
    }
  },
  {
    "code": "71911P8",
    "slug": "oneway-private-transfer-liberia-airport-to-your-selected-loc",
    "title": "OneWay Private Transfer - Liberia Airport To Your Selected Location",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "one-way",
    "rating": 4.85,
    "reviews": 73,
    "fromPrice": 130.86,
    "priceType": "UNIT",
    "durationMin": null,
    "durationMax": null,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/r/33/95/a5/b2/caption.jpg",
      "width": 720,
      "height": 480,
      "alt": "OneWay Private Transfer - Liberia Airport To Your Selected Location"
    }
  },
  {
    "code": "5490904P1",
    "slug": "private-transportation-costa-rica-guanacaste-airport-lir",
    "title": "Private Transportation Costa Rica Guanacaste Airport (LIR)",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "either",
    "rating": 5,
    "reviews": 69,
    "fromPrice": 5,
    "priceType": "PER_PERSON",
    "durationMin": 60,
    "durationMax": 120,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/15/4f/c4/34.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transportation Costa Rica Guanacaste Airport (LIR)"
    }
  },
  {
    "code": "131565P2",
    "slug": "liberia-int-airport-private-shuttle-one-way-or-round-trip",
    "title": "Liberia Int. Airport, Private Shuttle One Way or Round Trip",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "round-trip",
    "rating": 4.77,
    "reviews": 69,
    "fromPrice": 120,
    "priceType": "UNIT",
    "durationMin": null,
    "durationMax": null,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0b/c0/ab/ee.jpg",
      "width": 720,
      "height": 480,
      "alt": "Liberia Int. Airport, Private Shuttle One Way or Round Trip"
    }
  },
  {
    "code": "5766P21",
    "slug": "direct-transfer-liberia-airport-to-guanacaste-hotels",
    "title": "Direct Transfer Liberia Airport to Guanacaste Hotels",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "either",
    "rating": 4.75,
    "reviews": 59,
    "fromPrice": 35,
    "priceType": "PER_PERSON",
    "durationMin": null,
    "durationMax": null,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0b/0b/d6/71.jpg",
      "width": 720,
      "height": 480,
      "alt": "Direct Transfer Liberia Airport to Guanacaste Hotels"
    }
  },
  {
    "code": "8925P8",
    "slug": "book-transfer-from-lir-airport-to-jw-marriott-costa-elena-re",
    "title": "Book Transfer from LIR Airport to JW Marriott Costa Elena Resort",
    "origin": "LIR",
    "zone": "liberia-riu",
    "zoneName": "Liberia & RIU Guanacaste",
    "service": "private",
    "tripType": "either",
    "rating": 4.98,
    "reviews": 56,
    "fromPrice": 200,
    "priceType": "UNIT",
    "durationMin": null,
    "durationMax": null,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0b/81/d1/e5.jpg",
      "width": 720,
      "height": 480,
      "alt": "Book Transfer from LIR Airport to JW Marriott Costa Elena Resort"
    }
  },
  {
    "code": "8925P11",
    "slug": "private-transfer-tamarindo-beach-to-from-liberia-airport",
    "title": "Private Transfer Tamarindo Beach to/from Liberia Airport",
    "origin": "LIR",
    "zone": "tamarindo",
    "zoneName": "Tamarindo, Langosta & Playa Grande",
    "service": "private",
    "tripType": "either",
    "rating": 4.81,
    "reviews": 54,
    "fromPrice": 130,
    "priceType": "UNIT",
    "durationMin": 60,
    "durationMax": 60,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/10/83/f7/c4.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transfer Tamarindo Beach to/from Liberia Airport"
    }
  },
  {
    "code": "8925P15",
    "slug": "private-transfer-from-liberia-airport-to-secrets-papagayo-re",
    "title": "Private Transfer from Liberia Airport to Secrets Papagayo Resort",
    "origin": "LIR",
    "zone": "papagayo-coco",
    "zoneName": "Papagayo, Playas del Coco & Hermosa",
    "service": "private",
    "tripType": "either",
    "rating": 4.78,
    "reviews": 51,
    "fromPrice": 70,
    "priceType": "UNIT",
    "durationMin": 30,
    "durationMax": 30,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/r/34/1d/de/0c/caption.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transfer from Liberia Airport to Secrets Papagayo Resort"
    }
  },
  {
    "code": "378910P14",
    "slug": "shuttle-from-la-fortuna-to-san-jose",
    "title": "Shuttle from La Fortuna to San Jose",
    "origin": "SJO",
    "zone": "la-fortuna",
    "zoneName": "La Fortuna & Arenal",
    "service": "private",
    "tripType": "either",
    "rating": 4.8,
    "reviews": 49,
    "fromPrice": 55,
    "priceType": "PER_PERSON",
    "durationMin": 240,
    "durationMax": 240,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/26/85/12.jpg",
      "width": 720,
      "height": 480,
      "alt": "Shuttle from La Fortuna to San Jose"
    }
  },
  {
    "code": "476756P2",
    "slug": "private-transportation-guanacaste-liberia-airport",
    "title": "Private Transportation Guanacaste Liberia Airport",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "either",
    "rating": 4.98,
    "reviews": 48,
    "fromPrice": 5.6,
    "priceType": "PER_PERSON",
    "durationMin": 1800,
    "durationMax": 2700,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/e8/ee/35.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transportation Guanacaste Liberia Airport"
    }
  },
  {
    "code": "416411P3",
    "slug": "liberia-airport-to-hotels-round-trip-private-transfers",
    "title": "Liberia Airport to Hotels Round Trip Private Transfers",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "round-trip",
    "rating": 5,
    "reviews": 46,
    "fromPrice": 220,
    "priceType": "UNIT",
    "durationMin": 60,
    "durationMax": 180,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/13/d2/47/39.jpg",
      "width": 720,
      "height": 480,
      "alt": "Liberia Airport to Hotels Round Trip Private Transfers"
    }
  },
  {
    "code": "22702P15",
    "slug": "private-transportation-from-liberia-airport-to-la-fortuna",
    "title": "Private Transportation from LIBERIA AIRPORT to LA FORTUNA",
    "origin": "LIR",
    "zone": "la-fortuna",
    "zoneName": "La Fortuna & Arenal",
    "service": "private",
    "tripType": "either",
    "rating": 4.7,
    "reviews": 37,
    "fromPrice": 230,
    "priceType": "UNIT",
    "durationMin": 120,
    "durationMax": 180,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0c/00/33/5b.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transportation from LIBERIA AIRPORT to LA FORTUNA"
    }
  },
  {
    "code": "5766P26",
    "slug": "direct-transfer-guanacaste-hotel-to-liberia-airport",
    "title": "Direct Transfer Guanacaste Hotel to Liberia Airport",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "either",
    "rating": 4.68,
    "reviews": 34,
    "fromPrice": 35,
    "priceType": "PER_PERSON",
    "durationMin": null,
    "durationMax": null,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0b/0b/d3/e6.jpg",
      "width": 720,
      "height": 480,
      "alt": "Direct Transfer Guanacaste Hotel to Liberia Airport"
    }
  },
  {
    "code": "308019P2",
    "slug": "liberia-airport-lir-to-la-fortuna-arenal-private-vip-transfe",
    "title": "Liberia Airport (LIR) to La Fortuna/Arenal: Private VIP Transfer",
    "origin": "LIR",
    "zone": "la-fortuna",
    "zoneName": "La Fortuna & Arenal",
    "service": "private",
    "tripType": "either",
    "rating": 4.88,
    "reviews": 32,
    "fromPrice": 179,
    "priceType": "UNIT",
    "durationMin": 180,
    "durationMax": 180,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0b/e3/d1/71.jpg",
      "width": 720,
      "height": 480,
      "alt": "Liberia Airport (LIR) to La Fortuna/Arenal: Private VIP Transfer"
    }
  },
  {
    "code": "8925P7",
    "slug": "private-transfer-from-lir-airport-to-jw-marriott-guanacaste",
    "title": "Private Transfer From LIR Airport to JW Marriott Guanacaste",
    "origin": "LIR",
    "zone": "liberia-riu",
    "zoneName": "Liberia & RIU Guanacaste",
    "service": "private",
    "tripType": "either",
    "rating": 4.71,
    "reviews": 31,
    "fromPrice": 140,
    "priceType": "UNIT",
    "durationMin": 90,
    "durationMax": 90,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/r/33/65/7c/64/caption.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transfer From LIR Airport to JW Marriott Guanacaste"
    }
  },
  {
    "code": "348885P7",
    "slug": "private-transportation-from-liberia-airport-to-tamarindo",
    "title": "Private Transportation From Liberia Airport to Tamarindo",
    "origin": "LIR",
    "zone": "tamarindo",
    "zoneName": "Tamarindo, Langosta & Playa Grande",
    "service": "private",
    "tripType": "either",
    "rating": 4.97,
    "reviews": 29,
    "fromPrice": 27,
    "priceType": "PER_PERSON",
    "durationMin": 1,
    "durationMax": 30,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/10/3c/f7/a2.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transportation From Liberia Airport to Tamarindo"
    }
  },
  {
    "code": "5548768P1",
    "slug": "lir-liberia-airport-shuttle-service-to-your-hotel-or-airbnb",
    "title": "LIR Liberia Airport Shuttle Service to your Hotel or AirBnb",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "either",
    "rating": 4.88,
    "reviews": 26,
    "fromPrice": 5,
    "priceType": "UNIT",
    "durationMin": 30,
    "durationMax": 165,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/r/33/71/9f/90/caption.jpg",
      "width": 720,
      "height": 480,
      "alt": "LIR Liberia Airport Shuttle Service to your Hotel or AirBnb"
    }
  },
  {
    "code": "54087P21",
    "slug": "private-transfer-int-airport-liberia-to-la-fortuna-from-7-to",
    "title": "Private Transfer Int. Airport Liberia To La Fortuna From 7 to 10 passengers",
    "origin": "LIR",
    "zone": "liberia-riu",
    "zoneName": "Liberia & RIU Guanacaste",
    "service": "private",
    "tripType": "either",
    "rating": 5,
    "reviews": 24,
    "fromPrice": 308.86,
    "priceType": "UNIT",
    "durationMin": null,
    "durationMax": null,
    "freeCancellation": false,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/15/ed/97/ce.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transfer Int. Airport Liberia To La Fortuna From 7 to 10 passengers"
    }
  },
  {
    "code": "5548768P10",
    "slug": "round-trip-transfer-liberia-airport-to-your-hotel-or-airbnb",
    "title": "Round Trip Transfer Liberia Airport to Your Hotel or Airbnb",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "round-trip",
    "rating": 4.96,
    "reviews": 23,
    "fromPrice": 5,
    "priceType": "UNIT",
    "durationMin": 30,
    "durationMax": 165,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/r/33/8b/3f/7e/caption.jpg",
      "width": 720,
      "height": 480,
      "alt": "Round Trip Transfer Liberia Airport to Your Hotel or Airbnb"
    }
  },
  {
    "code": "63887P7",
    "slug": "private-airport-transfer-in-and-out-liberia-airport-guanacas",
    "title": "Private Airport Transfer In and Out Liberia Airport, Guanacaste",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "either",
    "rating": 5,
    "reviews": 22,
    "fromPrice": 165,
    "priceType": "UNIT",
    "durationMin": 30,
    "durationMax": 50,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/17/06/4c/3c.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Airport Transfer In and Out Liberia Airport, Guanacaste"
    }
  },
  {
    "code": "411920P6",
    "slug": "liberia-airport-private-transfer-one-way-round-trip-options",
    "title": "Liberia Airport Private Transfer – One Way & Round Trip Options",
    "origin": "LIR",
    "zone": "guanacaste",
    "zoneName": "Guanacaste (general)",
    "service": "private",
    "tripType": "round-trip",
    "rating": 5,
    "reviews": 21,
    "fromPrice": 60,
    "priceType": "PER_PERSON",
    "durationMin": 35,
    "durationMax": 60,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/15/7b/4a/05.jpg",
      "width": 720,
      "height": 480,
      "alt": "Liberia Airport Private Transfer – One Way & Round Trip Options"
    }
  },
  {
    "code": "110214P23",
    "slug": "transfer-from-liberia-airport-lir-to-planet-hollywood-beach-",
    "title": "Transfer from Liberia Airport (LIR) to Planet Hollywood Beach Resort",
    "origin": "LIR",
    "zone": "papagayo-coco",
    "zoneName": "Papagayo, Playas del Coco & Hermosa",
    "service": "private",
    "tripType": "either",
    "rating": 4.85,
    "reviews": 20,
    "fromPrice": 99.8,
    "priceType": "UNIT",
    "durationMin": 45,
    "durationMax": 45,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/09/aa/82/5d.jpg",
      "width": 720,
      "height": 480,
      "alt": "Transfer from Liberia Airport (LIR) to Planet Hollywood Beach Resort"
    }
  },
  {
    "code": "294950P3",
    "slug": "private-transportation-from-liberia-airport-to-tamarindo-bea",
    "title": "Private Transportation from Liberia Airport to Tamarindo Beach",
    "origin": "LIR",
    "zone": "tamarindo",
    "zoneName": "Tamarindo, Langosta & Playa Grande",
    "service": "private",
    "tripType": "either",
    "rating": 5,
    "reviews": 20,
    "fromPrice": 107,
    "priceType": "UNIT",
    "durationMin": 1,
    "durationMax": 120,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0f/df/f5/ba.jpg",
      "width": 720,
      "height": 480,
      "alt": "Private Transportation from Liberia Airport to Tamarindo Beach"
    }
  }
];
export const LOCAL_RENTALS: RentalProduct[] = [
  {
    "code": "17279P39",
    "slug": "4-seat-golf-cart-rental-tamarindo-langosta-jw-marriott-pinil",
    "title": "4 Seat Golf Cart Rental Tamarindo, Langosta & JW Marriott/Pinilla",
    "category": "golf-cart",
    "rating": 5,
    "reviews": 28,
    "freeCancellation": true,
    "image": {
      "url": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/7d/5a/17.jpg",
      "width": 720,
      "height": 480,
      "alt": "4 Seat Golf Cart Rental Tamarindo, Langosta & JW Marriott/Pinilla"
    }
  }
];
